### ISSUE TITLE
addon-contexts v1 NPM release roadmap

### ISSUE THREAD

**Issue by leoyli** [leoyli/addon-contexts#1]
## Roadmap to release v1.0.0
- [x] Polish type annotations
- [x] Properly configure the project
- [x] Publish the package on npm
- [x] Validate it is working on a user project

**Comment by leoyli** [comment]
Package have been released on NPM successfully, issue closed.

**Comment by leoyli** [comment]
Related to #2 #3 #4
